export const projects = [
  {
    slug: "troissix",
    title: "Site web — TroisSix",
    description: "Blog marketing avec chatbot IA intégré, newsletter et SEO on-page optimisé.",
    longDescription: "Site élaboré couvrant plusieurs domaines : blog, newsletter, page de contact, base de données SQL. Intégration d'un agent conversationnel IA via l'API Anthropic et n8n. SEO on-page soigné avec balises optimisées et structure sémantique complète.",
    year: "2025",
    role: "Développeur Full-stack",
    category: "Website Design",
    stack: ["PHP", "SQL", "Bootstrap", "JavaScript", "n8n", "Supabase", "API Anthropic", "Hostinger"],
    images: [],
  },
  {
    slug: "digimar",
    title: "Plateforme SEO — Digimar",
    description: "Plateforme SEO et outils digitaux avec blog, e-commerce, newsletter et audit SEO gratuit.",
    longDescription: "Projet le plus élaboré techniquement : e-commerce avec paiement Stripe, blog, newsletter, audit SEO gratuit. Implémentation avancée du SEO technique : Schema.org, Page Speed, balises structurées, Google Cloud API. Identité visuelle complète conçue sur Figma.",
    year: "2026",
    role: "Développeur Full-stack & Designer",
    category: "Website Design",
    stack: ["PHP", "SQL", "Bootstrap", "Stripe", "JavaScript", "Google Cloud API", "Schema.org", "Hostinger"],
    images: [],
  },
  {
    slug: "atelier-lumiere",
    title: "Site vitrine — Atelier Lumière",
    description: "Site vitrine performant avec blog, optimisé pour le référencement naturel.",
    longDescription: "Site simple et performant composé d'une page d'accueil et d'un blog. Meilleur score Search Console du portefeuille : optimisation technique poussée, temps de chargement minimal, SEO on-page rigoureux.",
    year: "2025",
    role: "Développeur & SEO",
    category: "Website Design",
    stack: ["HTML", "CSS", "Bootstrap", "JavaScript", "Hostinger"],
    images: [],
  },
  {
    slug: "mon-cv",
    title: "Application web — Mon CV",
    description: "Application web permettant d'analyser un CV via l'API Claude avec scoring ATS en temps réel.",
    longDescription: "Application full-stack permettant d'uploader un CV en PDF et d'obtenir une analyse détaillée via l'API Claude d'Anthropic. Interface soignée avec retour en temps réel, backend Node.js avec gestion des fichiers, et génération de recommandations personnalisées selon le poste visé.",
    year: "2025",
    role: "Développeur Full-stack",
    category: "App Desktop",
    stack: ["Node.js", "Express", "Claude API", "Git", "VPS"],
    images: [],
  },
  {
    slug: "lecteur-video-hmonster",
    title: "Composant UI — Lecteur vidéo",
    description: "Lecteur vidéo custom développé par itération pour Hmonster.",
    longDescription: "Développement d'un lecteur vidéo en Bootstrap par processus itératif : analyse des grandes institutions et concurrents, implémentation des boutons, accessibilité, sondages intégrés, support multilingue, overlay et sous-titres.",
    year: "2025",
    role: "Développeur UI/UX",
    category: "Website Design",
    stack: ["Bootstrap", "JavaScript", "HTML", "CSS"],
    images: [],
  },
  {
    slug: "configurateur-bateaux",
    title: "Configurateur — Bateaux",
    description: "Configurateur interactif de bateaux avec interface visuelle personnalisée.",
    longDescription: "Configurateur web permettant de choisir le nom d'un bateau et de rafraîchir dynamiquement la page principale avec les embarcations de chaque utilisateur. Design des visuels réalisé sur Illustrator.",
    year: "2025",
    role: "Développeur & Designer",
    category: "App Desktop",
    stack: ["PHP", "HTML", "CSS", "JavaScript", "Illustrator"],
    images: [],
  },
  {
    slug: "concept-salomon",
    title: "Web Design Concept — Salomon",
    description: "Concept de site pour un musée, maquette responsive.",
    longDescription: "Conception d'un concept de site web pour une institution muséale. Travail sur la hiérarchie visuelle, la navigation et l'adaptation responsive sur différents formats d'écran.",
    year: "2025",
    role: "Designer UI/UX",
    category: "Website Design",
    stack: ["Figma"],
    images: ["/images/Salomon.jpg"],
  },
  {
    slug: "concept-alpes",
    title: "Web Design Concept — Alpes",
    description: "Concept de site voyage basé sur la simplicité, maquette responsive.",
    longDescription: "Conception d'un concept de site web pour le voyage en montagne. Approche minimaliste axée sur la clarté visuelle et l'expérience utilisateur, avec adaptation responsive complète.",
    year: "2025",
    role: "Designer UI/UX",
    category: "Website Design",
    stack: ["Figma"],
    images: ["/images/Alpes.jpg"],
  },
  {
    slug: "concept-summer",
    title: "Web Design Concept — Summer",
    description: "Concept de site pour une marque de clothing urbain, maquette responsive.",
    longDescription: "Conception d'un concept de site e-commerce pour une marque de vêtements urbains. Direction artistique, choix typographiques et adaptation responsive sur mobile et desktop.",
    year: "2025",
    role: "Designer UI/UX",
    category: "Website Design",
    stack: ["Figma"],
    images: ["/images/Summer.jpg"],
  },
  {
    slug: "n8n-linkedin",
    title: "Automatisation — LinkedIn Carousel",
    description: "Automatisation de création de posts carrousel PDF pour LinkedIn via n8n.",
    longDescription: "Pipeline d'automatisation complète : veille d'un site d'actualité tech, génération de carrousels PDF, publication programmée deux fois par semaine via Buffer sur une page entreprise LinkedIn. Hébergé sur VPS Hostinger.",
    year: "2025",
    role: "Développeur Automatisation",
    category: "App Desktop",
    stack: ["n8n", "Make", "Buffer", "VPS", "Hostinger"],
    images: [],
  },
  {
    slug: "n8n-candidature",
    title: "Automatisation — Candidatures",
    description: "Scraping d'annonces JobUp avec génération automatique de CV et lettre de motivation.",
    longDescription: "Système de scraping des annonces JobUp.ch avec scoring automatique et génération personnalisée de CV et lettre de motivation en fonction du poste. Hébergé sur VPS Hostinger.",
    year: "2025",
    role: "Développeur Automatisation",
    category: "App Desktop",
    stack: ["n8n", "Node.js", "VPS", "Hostinger"],
    images: [],
  },
]
